general.import = ["~/.alacritty-colorscheme/themes/blood_moon.yaml"]

[colors.bright]
black = "#575b70"
blue = "#caa9fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[colors.normal]
black = "#000000"
blue = "#caa9fa"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "iosevka"
style = "Bold"

[font.bold_italic]
family = "iosevka"
style = "Bold Italic"

[font.italic]
family = "iosevka"
style = "Italic"

[font.normal]
family = "iosevka"
style = "Regular"

[window]
opacity = 0.75
