require('core.plugins.gruvbox')
require('core.plugins.lualine')
require('core.plugins.nvim-tree')
require('core.plugins.treesitter')
require('core.plugins.telescope')
require('core.plugins.gitsigns')
require('core.plugins.toggleterm')
require('core.plugins.autopairs')
