#!/bin/bash
if [ -z "$1" ]; then
    echo "<env_name> positional argument must be present."
    exit 1
fi
env_name=$1
env_id=$(docker ps -aqf "name=^${env_name}$")
if [ -z "${env_id}" ]; then
    echo "${GITHUB_TOKEN}" | docker login ghcr.io -u d3psi --password-stdin 
    docker pull ghcr.io/d3psi/dockers/development:master
    env_id=$(docker run \
        -dit \
        -e GH_TOKEN="${GH_TOKEN}" \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /home/d3psi/.git-credentials:/home/d3psi/.git-credentials \
        -v /home/d3psi/.gitconfig:/home/d3psi/.gitconfig \
        -v /home/d3psi/.gnupg:/home/d3psi/.gnupg \
        --name "${env_name}" \
        --network host \
        ghcr.io/d3psi/dockers/development:master \
        zsh)
fi
docker exec -it "${env_id}" zsh
