#!/bin/bash
if [ ! -z "$1" ]; then
    adb shell am start -a android.intent.action.DIAL -d "$1"
fi

if [[ $(ps aux | grep "scrcpy" | grep -v grep) ]]; then
    exit
fi

scrcpy -S --shortcut-mod ralt --power-off-on-close

